// Mocks generated by Mockito 5.4.4 from annotations
// in project_list_fliutter/test/src/modules/auth/unit/usecase/login_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:project_list_fliutter/src/modules/auth/domain/errors/error_datasource.dart'
    as _i5;
import 'package:project_list_fliutter/src/modules/auth/domain/repositories/login_repository.dart'
    as _i2;
import 'package:project_list_fliutter/src/modules/auth/infra/comm_packages/proto/user.pb.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ILoginRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockILoginRepository extends _i1.Mock implements _i2.ILoginRepository {
  MockILoginRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<(_i4.User?, _i5.CredentialsError?)> login(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            username,
            password,
          ],
        ),
        returnValue:
            _i3.Future<(_i4.User?, _i5.CredentialsError?)>.value((null, null)),
      ) as _i3.Future<(_i4.User?, _i5.CredentialsError?)>);
}
